<?php
session_start();
include '../database_driver/db.php';
    $_SESSION['logout']=44;
    $mid=$_SESSION['mid'];
    $_SESSION['mid']=$mid;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mandi Home</title>
    <link rel="icon" href="../assets/logo.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../assets/css/master.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"/>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script>
    $(document).ready(function(){
    $("#price").show();
    $("#farmerList").hide();
    $("#farmerUpdate").hide();
    $("#issues").hide();
  $("#hide").click(function(){
    // $("#farmerContent").hide();
  });
  $("#show").click(function(){
     $("#price").show();
     $("#photo").hide();
    $("#farmerList").hide();
    $("#farmerUpdate").hide();
    $("#issues").hide();
  });
});
    $(document).ready(function(){
        $("#price").show();
    $("#farmerList").hide();
    $("#farmerUpdate").hide();
    $("#issues").hide();
  $("#hide").click(function(){
    // $("#farmerContent").hide();
  });
  $("#show1").click(function(){
     $("#price").hide();
     $("#photo").hide();
    $("#farmerList").show();
    $("#farmerUpdate").hide();
    $("#issues").hide();
  });
});

    $(document).ready(function(){
    $("#price").show();
    $("#farmerList").hide();
    $("#farmerUpdate").hide();
    $("#issues").hide();
  $("#hide").click(function(){
    // $("#farmerContent").hide();
  });
  $("#show2").click(function(){
     $("#price").hide();
     $("#photo").hide();
    $("#farmerList").hide();
    $("#farmerUpdate").show();
    $("#issues").hide();
  });
});

    $(document).ready(function(){
    $("#price").show();
    $("#farmerList").hide();
    $("#farmerUpdate").hide();
    $("#issues").hide();
  $("#hide").click(function(){
    // $("#farmerContent").hide();
  });
  $("#show3").click(function(){
     $("#price").hide();
    $("#farmerList").hide();
    $("#farmerUpdate").hide();
    $("#photo").hide();
    $("#issues").show();
  });
});
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
        <a class="navbar-brand" href="#"><i class="fas fa-tractor"></i> Re_v_farm</a>
        <div class="my-2 my-lg-0" id="myProfileBtn">
            <button type="button" class="btn btn-outline-light btn-sm">
                <span class="fa fa-user"></span></button>
        </div>
        <div class="my-2 my-lg-0" id="myNotificationBtn">
            <button type="button" class="btn btn-outline-light btn-sm">
                <span class="fa fa-bell"></span></button>
        </div>
        <div class="my-2 my-lg-0" id="mySignoutBtn">
            <a  href="../SignoutHandler/lsignout.php"><button type="button" class="btn btn-danger btn-lg">
                <span class="fa fa-power-off"></span> Sign Out
            </button></a>
        </div>
    </nav>

    <!-- Body -->
    <div class="container-fluid">
        <div class="row">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr96qM5pnf-Sjyevi5CsgBEPPsVK07VBLQqA&usqp=CAU"  style="width: -webkit-fill-available;height:190px;
" alt="banner">
        <div class="col-md-3 col-sm-12">
            <div class="card">
                <div class="card-body text-center"><button type="button" class="btn btn-link btn-lg"
                        id="show">Market Price</button></div>
                <hr>
                <div class="card-body text-center"><button type="button" class="btn btn-link btn-lg"
                        id="show1">Farmer List</button></div>
                <hr>
                <div class="card-body text-center"><button type="button" class="btn btn-link btn-lg"
                        id="show2">Slot Booking Request's</button></div>
                <hr>
                <div class="card-body text-center"><button type="button" class="btn btn-link btn-lg"
                        id="show3">Issues</button></div>
            </div>
        </div>
        <div class="col-md-9 col-sm-12">
            <div class="card">
                <div class="card-body text-center">
                    <div id="price">
                        <h3>Market Price</h3>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>State</th>
                                    <th>District</th>
                                    <th>Market</th>
                                    <th>Commmodit</th>
                                    <th>Varity</th>
                                    <th>Arrival Date</th>
                                    <th>Min price</th>
                                    <th>Max price</th>
                                    <th>Modal price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Uttar Pradesh</td>
                                    <td>Lucknow</td>
                                    <td>Aminabad</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>19-02-2021</td>
                                    <td>1500</td>
                                    <td>1600</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Uttar Pradesh</td>
                                    <td>Lucknow</td>
                                    <td>Aminabad</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>2000</td>
                                    <td>2200</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Uttar Pradesh</td>
                                    <td>Lucknow</td>
                                    <td>Maiwaiya</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>11-02-2021</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Uttar Pardesh</td>
                                    <td>Ambedkar Nagar</td>
                                    <td>tanda</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>20-02-2021</td>
                                    <td>800</td>
                                    <td>1000</td>
                                    <td>800</td>
                                </tr>
                                <tr>
                                    <td>Uttar Pradesh</td>
                                    <td>Ambedkar Nagar</td>
                                    <td>katheri</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>3-02-2021</td>
                                    <td>500</td>
                                    <td>600</td>
                                    <td>500</td>
                                </tr>
                                <tr>
                                    <td>Uttar Pradesh</td>
                                    <td>Ghaziabad</td>
                                    <td>Bhootnath Market</td>
                                    <td>Paddy(Dhan)(Common)</td>
                                    <td>Other</td>
                                    <td>15-07-2021</td>
                                    <td>1750</td>
                                    <td>1770</td>
                                    <td>1750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Padampur</td>
                                    <td>Brinjal</td>
                                    <td>Brinjal</td>
                                    <td>16-02-2019</td>
                                    <td>1500</td>
                                    <td>1650</td>
                                    <td>1600</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Padampur</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1900</td>
                                    <td>2100</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Padampur</td>
                                    <td>Cauliflower</td>
                                    <td>Cauliflower</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1550</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Padampur</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Sohela</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>3000</td>
                                    <td>3200</td>
                                    <td>3100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Sohela</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1600</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Sohela</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1200</td>
                                    <td>1400</td>
                                    <td>1300</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bargarh</td>
                                    <td>Sohela</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>900</td>
                                    <td>1100</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bolangir</td>
                                    <td>Kantabaji</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>3000</td>
                                    <td>3000</td>
                                    <td>3000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Bolangir</td>
                                    <td>Kantabaji</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1500</td>
                                    <td>1500</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Boudh</td>
                                    <td>Bitter gourd</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>3500</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Boudh</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1600</td>
                                    <td>1400</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Boudh</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Boudh</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1500</td>
                                    <td>1400</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Boudh</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1500</td>
                                    <td>1400</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Boudh</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Boudh</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>700</td>
                                    <td>800</td>
                                    <td>700</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Khunthabandha</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1500</td>
                                    <td>1400</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Khunthabandha</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Khunthabandha</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1500</td>
                                    <td>1400</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Khunthabandha</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1500</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Khunthabandha</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Boudh</td>
                                    <td>Khunthabandha</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>700</td>
                                    <td>800</td>
                                    <td>700</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Banana - Green</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2500</td>
                                    <td>3000</td>
                                    <td>2800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Beans</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2400</td>
                                    <td>2600</td>
                                    <td>2500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Bhindi</td>
                                    <td>16-02-2019</td>
                                    <td>5000</td>
                                    <td>5500</td>
                                    <td>5200</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Bitter gourd</td>
                                    <td>Bitter Gourd</td>
                                    <td>16-02-2019</td>
                                    <td>5500</td>
                                    <td>6000</td>
                                    <td>5800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Brinjal</td>
                                    <td>Brinjal</td>
                                    <td>16-02-2019</td>
                                    <td>1500</td>
                                    <td>2000</td>
                                    <td>1800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Cucumbar(Kheera)</td>
                                    <td>Cucumbar</td>
                                    <td>16-02-2019</td>
                                    <td>1800</td>
                                    <td>2000</td>
                                    <td>1900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Potato</td>
                                    <td>Potato</td>
                                    <td>16-02-2019</td>
                                    <td>800</td>
                                    <td>1000</td>
                                    <td>900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Pumpkin</td>
                                    <td>Pumpkin</td>
                                    <td>16-02-2019</td>
                                    <td>1200</td>
                                    <td>1400</td>
                                    <td>1300</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Hindol</td>
                                    <td>Tomato</td>
                                    <td>Tomato</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Bhindi</td>
                                    <td>16-02-2019</td>
                                    <td>4000</td>
                                    <td>4500</td>
                                    <td>4500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Bitter gourd</td>
                                    <td>Bitter Gourd</td>
                                    <td>16-02-2019</td>
                                    <td>4000</td>
                                    <td>4600</td>
                                    <td>4500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Brinjal</td>
                                    <td>Brinjal</td>
                                    <td>16-02-2019</td>
                                    <td>1900</td>
                                    <td>2100</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Cabbage</td>
                                    <td>Cabbage</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1600</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Cauliflower</td>
                                    <td>Cauliflower</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1600</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Cucumbar(Kheera)</td>
                                    <td>Cucumbar</td>
                                    <td>16-02-2019</td>
                                    <td>2900</td>
                                    <td>3200</td>
                                    <td>3000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Green Chilli</td>
                                    <td>Green Chilly</td>
                                    <td>16-02-2019</td>
                                    <td>4900</td>
                                    <td>5500</td>
                                    <td>5000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Onion</td>
                                    <td>Onion</td>
                                    <td>16-02-2019</td>
                                    <td>1600</td>
                                    <td>2000</td>
                                    <td>1800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Potato</td>
                                    <td>Potato</td>
                                    <td>16-02-2019</td>
                                    <td>900</td>
                                    <td>1100</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Dhenkanal</td>
                                    <td>Kamakhyanagar</td>
                                    <td>Pumpkin</td>
                                    <td>Pumpkin</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1200</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Kasinagar</td>
                                    <td>Banana</td>
                                    <td>Banana - Ripe</td>
                                    <td>16-02-2019</td>
                                    <td>2500</td>
                                    <td>3000</td>
                                    <td>3000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Kasinagar</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2500</td>
                                    <td>3000</td>
                                    <td>3000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Kasinagar</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1500</td>
                                    <td>2000</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Kasinagar</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>500</td>
                                    <td>600</td>
                                    <td>600</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Parlakhemundi</td>
                                    <td>Apple</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>8000</td>
                                    <td>10000</td>
                                    <td>10000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Parlakhemundi</td>
                                    <td>Banana</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2500</td>
                                    <td>3000</td>
                                    <td>3000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Parlakhemundi</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1500</td>
                                    <td>2000</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Parlakhemundi</td>
                                    <td>Ox</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>15000</td>
                                    <td>20000</td>
                                    <td>20000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Gajapati</td>
                                    <td>Parlakhemundi</td>
                                    <td>Tomato</td>
                                    <td>Tomato</td>
                                    <td>16-02-2019</td>
                                    <td>1600</td>
                                    <td>2000</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Ganjam</td>
                                    <td>Bhanjanagar</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1600</td>
                                    <td>2000</td>
                                    <td>1800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Ganjam</td>
                                    <td>Bhanjanagar</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1300</td>
                                    <td>1500</td>
                                    <td>1400</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Ganjam</td>
                                    <td>Bhanjanagar</td>
                                    <td>Paddy(Dhan)(Common)</td>
                                    <td>Common</td>
                                    <td>16-02-2019</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Ganjam</td>
                                    <td>Bhanjanagar</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>800</td>
                                    <td>1100</td>
                                    <td>900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Ganjam</td>
                                    <td>Bhanjanagar</td>
                                    <td>Rice</td>
                                    <td>Common</td>
                                    <td>16-02-2019</td>
                                    <td>2000</td>
                                    <td>2200</td>
                                    <td>2100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Ganjam</td>
                                    <td>Bhanjanagar</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>700</td>
                                    <td>1000</td>
                                    <td>800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Koraput</td>
                                    <td>Jeypore(Kotpad)</td>
                                    <td>Paddy(Dhan)(Common)</td>
                                    <td>Common</td>
                                    <td>16-02-2019</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkanagiri</td>
                                    <td>Banana - Green</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>3000</td>
                                    <td>3200</td>
                                    <td>3100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkanagiri</td>
                                    <td>Bitter gourd</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>4000</td>
                                    <td>4200</td>
                                    <td>4100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkanagiri</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2000</td>
                                    <td>2200</td>
                                    <td>2100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkanagiri</td>
                                    <td>Paddy(Dhan)(Common)</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkangiri(Korakunda)</td>
                                    <td>Banana - Green</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>3000</td>
                                    <td>3200</td>
                                    <td>3100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkangiri(Korakunda)</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2000</td>
                                    <td>2200</td>
                                    <td>2100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkangiri(Korakunda)</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1100</td>
                                    <td>1300</td>
                                    <td>1200</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkangiri(Korakunda)</td>
                                    <td>Green Chilli</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>4000</td>
                                    <td>4200</td>
                                    <td>4100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Malkangiri</td>
                                    <td>Malkangiri(Korakunda)</td>
                                    <td>Paddy(Dhan)(Common)</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Apple</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>9000</td>
                                    <td>10000</td>
                                    <td>9500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Apple</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>8000</td>
                                    <td>9000</td>
                                    <td>8500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>3300</td>
                                    <td>3500</td>
                                    <td>3400</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Egg</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1060</td>
                                    <td>1080</td>
                                    <td>1070</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Fish</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>17000</td>
                                    <td>19000</td>
                                    <td>18000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Paddy(Dhan)(Common)</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1550</td>
                                    <td>1750</td>
                                    <td>1750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Rice</td>
                                    <td>Common</td>
                                    <td>16-02-2019</td>
                                    <td>2500</td>
                                    <td>2530</td>
                                    <td>2520</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Mayurbhanja</td>
                                    <td>Karanjia</td>
                                    <td>Rice</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2450</td>
                                    <td>2470</td>
                                    <td>2460</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Nowarangpur</td>
                                    <td>Nawarangpur</td>
                                    <td>Broken Rice</td>
                                    <td>Broken Rice</td>
                                    <td>16-02-2019</td>
                                    <td>800</td>
                                    <td>1300</td>
                                    <td>1200</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Nowarangpur</td>
                                    <td>Nawarangpur</td>
                                    <td>Maize</td>
                                    <td>Hybrid/Local</td>
                                    <td>16-02-2019</td>
                                    <td>1400</td>
                                    <td>1550</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>5400</td>
                                    <td>5600</td>
                                    <td>5500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1480</td>
                                    <td>1520</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>650</td>
                                    <td>800</td>
                                    <td>750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>2500</td>
                                    <td>2600</td>
                                    <td>2600</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Green Chilli</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>2500</td>
                                    <td>2600</td>
                                    <td>2600</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1000</td>
                                    <td>1020</td>
                                    <td>1020</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>850</td>
                                    <td>900</td>
                                    <td>880</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Dungurapalli</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>680</td>
                                    <td>800</td>
                                    <td>750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Pandkital</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>5400</td>
                                    <td>5600</td>
                                    <td>5500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Pandkital</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1380</td>
                                    <td>1500</td>
                                    <td>1450</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Pandkital</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>980</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Pandkital</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>2500</td>
                                    <td>2600</td>
                                    <td>2600</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Pandkital</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>850</td>
                                    <td>1000</td>
                                    <td>950</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Pandkital</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>850</td>
                                    <td>1000</td>
                                    <td>950</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sonepur</td>
                                    <td>Pandkital</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>700</td>
                                    <td>780</td>
                                    <td>750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Banana - Green</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Bhindi(Ladies Finger)</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Black Gram (Urd Beans)(Whole)</td>
                                    <td>Local</td>
                                    <td>16-02-2021</td>
                                    <td>5600</td>
                                    <td>9000</td>
                                    <td>8000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Black Gram (Urd Beans)(Whole)</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>5600</td>
                                    <td>9000</td>
                                    <td>8000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1500</td>
                                    <td>2000</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Capsicum</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Carrot</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1000</td>
                                    <td>2000</td>
                                    <td>2000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Cucumbar(Kheera)</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>French Beans (Frasbean)</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Onion</td>
                                    <td>Onion</td>
                                    <td>16-02-2021</td>
                                    <td>1500</td>
                                    <td>1500</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1500</td>
                                    <td>1500</td>
                                    <td>1500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Orange</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>6000</td>
                                    <td>6000</td>
                                    <td>6000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Orange</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>6000</td>
                                    <td>6000</td>
                                    <td>6000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Orange</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>6000</td>
                                    <td>6000</td>
                                    <td>6000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Paddy(Dhan)(Common)</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1750</td>
                                    <td>1770</td>
                                    <td>1750</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Rice</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>3500</td>
                                    <td>3500</td>
                                    <td>3500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Sugar</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                    <td>4000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                    <td>1000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Wheat</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>1735</td>
                                    <td>3000</td>
                                    <td>3000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Bonai</td>
                                    <td>Wheat Atta</td>
                                    <td>Wheat Atta</td>
                                    <td>16-02-2021</td>
                                    <td>3500</td>
                                    <td>4000</td>
                                    <td>3500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Panposh</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>600</td>
                                    <td>1000</td>
                                    <td>900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Panposh</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>700</td>
                                    <td>1000</td>
                                    <td>900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Panposh</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2021</td>
                                    <td>800</td>
                                    <td>1200</td>
                                    <td>1100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Panposh</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>700</td>
                                    <td>1000</td>
                                    <td>900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Banana - Green</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2500</td>
                                    <td>3000</td>
                                    <td>2800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Brinjal</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>800</td>
                                    <td>1000</td>
                                    <td>900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Cabbage</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>700</td>
                                    <td>1000</td>
                                    <td>800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Capsicum</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2800</td>
                                    <td>3000</td>
                                    <td>2900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Carrot</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>2200</td>
                                    <td>3000</td>
                                    <td>2500</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Cauliflower</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1800</td>
                                    <td>2000</td>
                                    <td>1900</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Green Chilli</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>5000</td>
                                    <td>7000</td>
                                    <td>6000</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Onion</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>1000</td>
                                    <td>1200</td>
                                    <td>1100</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Potato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>700</td>
                                    <td>1000</td>
                                    <td>800</td>
                                </tr>
                                <tr>
                                    <td>Odisha</td>
                                    <td>Sundergarh</td>
                                    <td>Sargipali</td>
                                    <td>Tomato</td>
                                    <td>Other</td>
                                    <td>16-02-2019</td>
                                    <td>500</td>
                                    <td>700</td>
                                    <td>600</td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div id="farmerList">
                    <?php 
                    $res=mysqli_query($con,"select * from mredg where mid='$mid'");
                    $far=mysqli_fetch_assoc($res);
                    $district=$far['district'];
                    $lr=mysqli_query($con,"select * from fredg");
                    while ($arr1 = $lr->fetch_assoc())
                            {
                                ?>
                                <table class="table table-success" style="background-color: #5cb85c;color: white;">
                                    <thead style="font-size: 12px;">
                                    <tr>
                                        <th>Picture</th>
                                        <th>Name</th>
                                        <th>City</th>
                                        <th>District</th>
                                    </tr>
                                    </thead>
                                    <tr>
                                        <td><img src="<?php echo $arr1['pic']; ?>"style="width: 40px;"></td>
                                        <td><?php echo $arr1['name']; ?> </td>
                                        <td><?php echo $arr1['city']; ?> </td>
                                        <td><?php echo $arr1['district']; ?> </td>
                                    </tr>
                                </table>
                                 <?php
                            // echo $arr1['name'];      
                            // echo "string"; 
                            }   
                            ?>
                    </div>
                    <div id="farmerUpdate">
                        <table class="table table-success" style="background-color: #5cb85c;color: white;">
                                    <thead style="font-size: 12px;">
                                    <tr>
                                        <th>Picture</th>
                                        <th>Name</th>
                                        <th>City</th>
                                        <th>District</th>
                                    </tr>
                                    </thead>
                        <?php
                        while ($arr1 = $lr->fetch_assoc())
                            {
                                ?>
                                
                                    <tr>
                                        <td><img src="<?php echo $arr1['pic']; ?>"style="width: 40px;"></td>
                                        <td><?php echo $arr1['name']; ?> </td>
                                        <td><?php echo $arr1['city']; ?> </td>
                                        <td><?php echo $arr1['district']; ?> </td>
                                    </tr>
                                
                                 <?php
                            // echo $arr1['name'];      
                            // echo "string"; 
                            }   
                            ?>
</table>
                    </div>
                    <div id="issues">
                        <table class="table table-hover">
                            <thead>
                              <tr>
                                <th>Profile Pic</th>
                                <th>Issuer Name</th>
                                <th>Description</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td><img src="https://thispersondoesnotexist.com/" class="rounded" height="32px" width="32px" alt="Cinque Terre"></td>
                                <td>Sampark Behera</td>
                                <td>The price is higher than expected.</td>
                              </tr>
                              <tr>
                                <td><img src="https://thispersondoesnotexist.com/" class="rounded" height="32px" width="32px" alt="Cinque Terre"></td>
                                <td>Kalia Mohato</td>
                                <td>Government should focus on decentralized teaching of farmers rather than waiving off their loans 
                                    because this is going to help them only once but providing them with knowledge will help them all 
                                    through the life.</td>
                              </tr>
                              <tr>
                                <td><img src="https://thispersondoesnotexist.com/" class="rounded" height="32px" width="32px" alt="Cinque Terre"></td>
                                <td>Dev Prasad</td>
                                <td> Monsoon dependant agriculture makes it susceptible to the problems of Irrigation which is still inadequate despite measures taken by the government.</td>
                              </tr>
                            </tbody>
                          </table>
                    </div>               
                </div>
            </div>
        </div>
    </div>
    </div>
</body>